// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetIndex(arg1) {
  return window['go']['api']['Api']['GetIndex'](arg1);
}

export function GetIndexCollectionGroup() {
  return window['go']['api']['Api']['GetIndexCollectionGroup']();
}

export function GetScriptContent(arg1) {
  return window['go']['api']['Api']['GetScriptContent'](arg1);
}

export function ListIndexCollection(arg1) {
  return window['go']['api']['Api']['ListIndexCollection'](arg1);
}

export function ListScript(arg1) {
  return window['go']['api']['Api']['ListScript'](arg1);
}

export function SaveIndex(arg1, arg2) {
  return window['go']['api']['Api']['SaveIndex'](arg1, arg2);
}

export function SaveIndexCollection(arg1) {
  return window['go']['api']['Api']['SaveIndexCollection'](arg1);
}

export function SaveIndexCollectionGroup(arg1) {
  return window['go']['api']['Api']['SaveIndexCollectionGroup'](arg1);
}

export function SaveScript(arg1) {
  return window['go']['api']['Api']['SaveScript'](arg1);
}

export function SaveScriptContent(arg1, arg2) {
  return window['go']['api']['Api']['SaveScriptContent'](arg1, arg2);
}

export function Startup(arg1, arg2) {
  return window['go']['api']['Api']['Startup'](arg1, arg2);
}
