// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {entity} from '../models';
import {context} from '../models';
import {dig} from '../models';

export function GetIndex(arg1:string):Promise<Array<entity.Index>>;

export function GetIndexCollectionGroup():Promise<entity.IndexCollectionGroup>;

export function GetScriptContent(arg1:string):Promise<string>;

export function ListIndexCollection(arg1:Array<string>):Promise<Array<entity.IndexCollection>>;

export function ListScript(arg1:Array<string>):Promise<Array<entity.Script>>;

export function SaveIndex(arg1:string,arg2:Array<entity.Index>):Promise<void>;

export function SaveIndexCollection(arg1:entity.IndexCollection):Promise<entity.IndexCollection>;

export function SaveIndexCollectionGroup(arg1:entity.IndexCollectionGroup):Promise<void>;

export function SaveScript(arg1:entity.Script):Promise<entity.Script>;

export function SaveScriptContent(arg1:string,arg2:string):Promise<void>;

export function Startup(arg1:context.Context,arg2:dig.Container):Promise<void>;
